### PR TITLE
fix verysillycat's badge and change to .png instead of .webp

### PR DESCRIPTION
**Pull request by verysillycat**
i fixed my badge and changed it to .png instead of .webp

### CODE REVIEW

**Comment by verticalsync** [comment]
webp assets work just fine

**Comment by verysillycat** [comment]
bro has to manually fix it now

**Comment by verysillycat** [comment]
if u would fucking accepted this PR all badges would be fixed bc i broke them yesterday btw

**Comment by verticalsync** [comment]
Superseded by 184f199237aaeea68e0710850c8b41203ac79380

**Comment by verysillycat** [comment]
> Superseded by [32a3e1f](https://github.com/verticalsync/Suncord/commit/32a3e1fd6d12bb6e47b264c2cc3a8b30ca8df945)

i think you replied to the wrong PR blud

**Pull request closed without merging**
