### PR TITLE
VencordToolbox ---> SuncordToolbox

### PR DESCRIPTION
**Pull request by verysillycat**
- make vencord's shiggy be suncord logo
- when opened it's a waxing crescent moon

- fully renamed to Suncord

https://github.com/verticalsync/Suncord/assets/126973723/17befa83-bd44-4e72-80b7-c963949482ea
- it's almost 3 am and i should go to sleep

### CODE REVIEW

**Comment by verticalsync** [comment]
i didnt do this for a reason, so people who move from vencord it works just fine

**Comment by verysillycat** [comment]
> i didnt do this for a reason, so people who move from vencord it works just fine

yeah i know, you're not supposed to change the entirely of vencord to suncord, but i figured it just the toolbar would look better, and also i figured that most of the people that come from vencord are probably going to know that it's the toolbar from vencord, even if they dont, they can just click on it

**Comment by verysillycat** [comment]
if they dont see it after importing config from vencord, they can just notice that and then just search toolbox on their plugins search bar and it will appear, and also the toolbox is just a toolbox, a shortcut, not that important

**Comment by prettylittlelies** [comment]
useless commit shut UP Pcortex

**Comment by verysillycat** [comment]
> useless pr shut UP Pcortex

shiver timbers!!!!

**Comment by thororen1234** [comment]
> i didnt do this for a reason, so people who move from vencord it works just fine

migratePluginSettings("SuncordToolbox", "VencordToolbox")

**Comment by verticalsync** [comment]
Superseded by b0105082dcb51a3883e89ca5e73c7a91897451c4

**Pull request closed without merging**
